### ISSUE TITLE
Automatic-Module-Name: Calling all Java Library Maintainers

### ISSUE THREAD

**Issue by froque** [premium-minds/billy#180]
http://branchandbound.net/blog/java/2017/12/automatic-module-name/

- [x] must fix #179 first 
- [x] must be merged: #315
- [x] must upgrade fop #158 
- [x] https://youtrack.jetbrains.com/issue/IDEA-183692
  - next Intellij IDEA version, expected late July 2022 
- [x] ~https://issues.apache.org/jira/browse/XALANJ-2632~ (This should not be needed with [fop bump](https://github.com/premium-minds/billy/pull/354) that [no longer requires xalan](https://issues.apache.org/jira/browse/FOP-3085))
  - https://stackoverflow.com/questions/54682417/unable-to-derive-module-descriptor-provider-class-x-not-in-module
  - https://github.com/apache/xalan-java/pull/1
  - with java.version set to 11 and Automatic-Module-Name defined in each maven module:
```
$ JAVA_HOME=/usr/lib/jvm/java-1.17.0-openjdk-amd64 mvn -q -DskipTests clean install                                                                                                                 130 ↵
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.4.0:jar (attach-javadocs) on project billy-gin: Execution attach-javadocs of goal org.apache.maven.plugins:maven-javadoc-plugin:3.4.0:jar failed: Unable to derive module descriptor for /home/froque/.m2/repository/xalan/xalan/2.7.2/xalan-2.7.2.jar: Provider class org.apache.bsf.BSFManager not in module -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the '-e' switch
[ERROR] Re-run Maven using the '-X' switch to enable verbose output
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn [args] -r
```
